### ISSUE TITLE
error with nginx config

### ISSUE THREAD

**Issue by johnjaylward** [rgl/gitlab-source-link-proxy#3]
when I paste the config into the nginx config and restart, I get the following error:
> duplicate location "/" in /var/opt/gitlab/nginx/conf/gitlab-http.conf:136

I instead changed the location block to look like:
```
  location ~ (.*/raw/.*) {
    if ($http_user_agent ~ "(Microsoft-Symbol-Server|SourceLink)") {
      #proxy_set_header Authorization "Basic cm9vdDpwYXNzd29yZA==";
      proxy_pass http://127.0.0.1:7000;
      break;
    }
    proxy_cache off;
    proxy_pass  http://gitlab-workhorse;
  }
```

It works because source link should only be requesting the RAW urls. I also used the user-agent match change from #2 with no issues

**Comment by rgl** [comment]
You're supposed to change the existing location section as this diff:

https://github.com/rgl/gitlab-vagrant/blob/master/gitlab-http.conf-gitlab-source-link-proxy.patch

I will make this more explicit in the README.

**Comment by rgl** [comment]
This was fixed in https://github.com/rgl/gitlab-source-link-proxy/commit/0d469626b64ec9e1184ab5bb4ca6ef8c286aee36
